/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'taisho6339' at '16/05/17 7:25' with Gradle 2.1
 *
 * @author taisho6339, @date 16/05/17 7:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
